9ТЗ
IcelandicMan/java-filmorate pull request #5
Opened 2023-05-22 12:20 UTC by IcelandicMan

2023-05-22 13:21 UTC, IcelandicMan commented
Добавлен проект в ветку для проверки

2023-05-22 16:06 UTC, YazykovMikhail requested changes

2023-05-22 16:06 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank(message = "Логин не может содержать пробелы")
посмотри какая между ними разница и осавь что то одно

2023-05-22 16:06 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            user.setName(user.getLogin());
вот тут хотелось бы увидеть логирвоани, произошел бизнес процесс. Как потом разобраться что было имя или нет.

2023-05-22 16:06 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Logger log = LoggerFactory.getLogger(FilmController.class);
Совет по логированию
стоит всегда догирвоать как минимум входные данные и ответ.
Касается всех эндпоинтов.
Ты идешь смотреть логи кгда что то сломалось. Нельзя отслкдить поломку? если не видет ьчто пришло, что ушло и что происходило.

2023-05-22 16:06 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film.setId(nextFilmId++);
метод долден отвечать за свое id.
А ты тут увеличиваешь id для следующег ометода. А сам используешь уже готово.

++idCounter

2023-05-22 16:06 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int nextFilmId = 1;
лучше idCounter = 0;
каждый метод долже нсам отвечать за свое id

2023-05-22 16:09 UTC, YazykovMikhail requested changes

2023-05-22 16:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
Лучше всетаки хранить в Map, уже же есть опыт ;)

2023-05-23 08:48 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean hasValidationErrors(Film film) {
Удалил доп Валидатор и аннотацию. Добавил параметр и проверку в переименованный метод isValid()

2023-05-23 08:51 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(max = 200, message = "Максимальная длина описания - 200 символов")
Понял комментарий, просто в ТЗ не было требования, что он обязательно должен что-то содержать

2023-05-23 08:52 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            user.setName(user.getLogin());
Добавил логирование в метод и логирования при получении и выводе информации в других методах

2023-05-23 08:52 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
Изменено на Map

2023-05-23 15:17 UTC, YazykovMikhail commented
Комментарии которые ты поправил отмечай "решенными"

2023-05-23 15:18 UTC, YazykovMikhail approved these changes

2023-05-23 15:18 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Map<Integer, User> users = new HashMap<>();
final

2023-05-30 09:05 UTC, merged