Add friends likes
IcelandicMan/java-filmorate pull request #6
Opened 2023-06-03 08:14 UTC by IcelandicMan

2023-06-04 18:11 UTC, YazykovMikhail requested changes

2023-06-04 18:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public List<User> getUserFriends(long userId) {
в сторадже просто CRUD методы. 
А вот эта логика с общими друзьяи, это логика для сериса. 
Примерно вот так может выглядеть метод в сервисе.

```
public List<User> getCommonFriends(long id, long otherId) {
		final User user = storage.get(id);
		final User other = storage.get(otherId);
		final Set<Long> friends = user.getFriendIds();
		final Set<Long> otherFriends = other.getFriendIds();

		return friends.stream()
				.filter(otherFriends::contains)
				.map(userId -> storage.get(userId))
				.collect(Collectors.toList());

```	}

2023-06-04 18:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (updatedUser.getLogin() != null) {
Вообще часитичное обноелние это у метода Path, а ты вызываешь Put там обычно идет полное обновление.
Вот эти все проверки тоже должны быть в сервисе. Сторадж просто дает CRUD операции до базы данных. 
Все уже должно дыть готово, тем более это бизнес логика, и как раз для нее есть уровень сервисов. Вынеси туда проверки

2023-06-04 18:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    public InMemoryUserStorage getUserStorage() {
такого метода не должно существовать, все методы проходят через сервис

2023-06-04 18:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public InMemoryFilmStorage getFilmStorage() {
Такого метода не должно существовать. 
Все методы сначлаа приходят в сервис, потом идут дальше

2023-06-04 18:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (updatedFilm.getName() != null) {
Вообще часитичное обноелние это у метода Path, а ты вызываешь Put там обычно идет полное обновление. 
Так что можно целиком обновлять фильм.
И в любом случае даже если и желаьб эти проверки, то на уровне сервиса.

2023-06-04 18:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        isValidFilmId(updatedFilm.getId());
ты тут проверяешь что есть обьект. А потом еще ниже есть код
Film film = films.get(id);
который так же пробегается и ищет этот обеькт. Я показывал как стоит делать. 
Сразу получаешь обьект, и проверяешь null или нет. 
У тебя будет 1 поиск вместо 2 поисков.

2023-06-04 18:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private void assignNameIfEmpty(User user) {
это метод бизнес логики, ему нчеего делать в слое для хранения данных.
За бизнес логику отвечает сервис

2023-06-04 18:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public void isValidUserId(long id) {
этот метод улчше убрать. Там где надо вызывай get и проверяй результат

2023-06-04 18:11 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public void isValidFilmId(long id) {
этот метод улчше убрать. Там где надо вызывай get и проверяй результат

2023-06-05 07:19 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
Добавлен 
com.fasterxml.jackson.annotation.JsonIgnore

2023-06-05 07:19 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friends = new HashSet<>();
Добавлен
com.fasterxml.jackson.annotation.JsonIgnore

2023-06-05 07:42 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Исправлено

2023-06-05 07:42 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    private final InMemoryUserStorage userStorage;
Исправлено

2023-06-05 07:43 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +}
Исправлено. Изначально был верный вариант, но я сделал по ТЗ, а там только создание, обновление, удаление было

2023-06-05 07:43 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +}
Исправлено

2023-06-05 07:50 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public List<User> getUserFriends(long userId) {
Этот метод создает список не общих друзей между двумя пользователями,  а просто друзей одного пользователя, но хорошо, я его вынесу в сервис, хотя, честно? не понимаю почему, ведь это относится к полям (списку) класса

2023-06-06 09:18 UTC, IcelandicMan commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        userStorage.isValidUserId(userId);
Исправил на получение информации методом getuser(id), который или возвращает User или выбрасывает исключение

2023-06-07 10:05 UTC, YazykovMikhail approved these changes

2023-07-04 08:29 UTC, merged