feat: Добавлен запрос для предоставления рекомендуемых фильмов
IcelandicMan/java-filmorate pull request #8
Opened 2023-07-19 11:19 UTC by IcelandicMan

2023-07-21 11:03 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/storage/recommendation/RecommendationDbStorage.java
> +@Slf4j
Аннотация есть, логов не вижу

2023-07-21 11:05 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/storage/recommendation/RecommendationDbStorage.java
> +                "SELECT f.id, f.name, f.description, f.releaseDate, f.duration, f.mpa_id, " +
За этот запрос отдельный лайк)

2023-07-21 11:05 UTC, lykkeee requested changes
Всё супер, одну аннотацию только поправить

2023-07-23 20:22 UTC, lykkeee approved these changes
Отлично!

2023-07-25 11:28 UTC, Konstantin-Vyazovoi approved these changes
Всё отлично

2023-07-25 17:18 UTC, merged